### PR TITLE
Add plugin configuration for MongooseIM

### PR DESCRIPTION
**Pull request by oli-g**
Hi @anryko I'm adding support for [MongooseIM metrics](https://mongooseim.readthedocs.io/en/latest/developers-guide/REST-interface-to-metrics/).

MongooseIM metrics can be grabbed by CollectD thanks to this configuration snippet:

```
LoadPlugin curl_json
<Plugin "curl_json">
          <URL "http://<MONGOOSEIM_IP>:5280/api/metrics/all">
              Instance "mongooseim"
              <Key "metrics/sessionCount">
                  Type "absolute"
              </Key>
              <Key "metrics/*/count">
                  Type "absolute"
              </Key>
              <Key "metrics/*/one">
                  Type "absolute"
              </Key>
          </URL>
</Plugin>
```

The dashboard I added already works, but I would suggest a little change in your code. Check my comments 😉 .

Thank you for this great tool!

### CODE REVIEW

**Comment by anryko** [comment]
Thanks @oli-g 
Could you add a collectd config example file too? To work around the issue with plugin name I would suggest to use collectd precache chain modifications and rename metric before passing it to influxdb. I encountered the same case with [kafka plugin](https://github.com/anryko/grafana-influx-dashboard/blob/master/examples/collectd.conf.d/kafka.conf).
I will experiment with your suggestion for configurable series and see what I can do in the next couple of days.

**Comment by oli-g** [comment]
Oh I missed that `PreCacheChain` stuff on Collectd! Thank you, it seems to be what I was looking for, so maybe the change I suggested is not that needed anymore!
I will update this PR soon with your suggestion.

**Comment by anryko** [comment]
Nice! Could you please update [README](https://github.com/anryko/grafana-influx-dashboard#supported-metrics) and I'll merge it.

**Comment by anryko** [comment]
thank you.

**Pull request merged**
